mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
       id-type: auto
       logic-delete-value: 1
       logic-not-delete-value: 0

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 12010

spring:
  application:
    name: shopping-elasticsearch
#  datasource:
#    url: jdbc:mysql://192.168.56.10:3306/shopping_pms?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

